preload = ~/.config/wallpapers/forest-background-4k.jpg
#wallpaper = DP-2, ~/.config/wallpapers/forest-green.jpg
wallpaper {
    monitor = DP-2
    path = ~/.config/wallpapers/forest-background-4k.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = ~/.config/wallpapers/forest-background-4k.jpg
    fit_mode = cover
}
